/// <summary>
/// 物品类型枚举（背包Tab分类）
/// 对应protobuf生成枚举，用于区分道具大类，控制背包分页、显示逻辑、过滤规则
/// </summary>
public enum ItemMainType
{
    /// <summary>无效类型，默认值</summary>
    ItemType_Invalid = 0,
    /// <summary>消耗品</summary>
    ItemType_Consumables = 1,
    /// <summary>装备</summary>
    ItemType_Equip = 2,
    /// <summary>材料</summary>
    ItemType_Material = 3,
    /// <summary>卡牌</summary>
    ItemType_Card = 4,
    /// <summary>背包其他杂项</summary>
    ItemType_BagOther = 5,
    /// <summary>时装</summary>
    ItemType_Fashion = 6,
    /// <summary>货币类道具</summary>
    ItemType_Money = 7,
    /// <summary>菜谱</summary>
    ItemType_CookBook = 8,
    /// <summary>任务道具</summary>
    ItemType_Task = 9,
    /// <summary>生活装备</summary>
    ItemType_LifeEquip = 10,
    /// <summary>头饰图纸</summary>
    ItemType_HeadwearDrawing = 11,
    /// <summary>器件/装置道具</summary>
    ItemType_Device = 12,
    /// <summary>头像</summary>
    ItemType_HeadPortrait = 13,
    /// <summary>载具</summary>
    ItemType_Carrier = 14,
    /// <summary>载具经验书</summary>
    ItemType_CarrierExpBook = 15,
    /// <summary>卡牌碎片</summary>
    ItemType_CardPatch = 16,
    /// <summary>称号</summary>
    ItemType_Title = 17,
    /// <summary>商品</summary>
    ItemType_Commodity = 18,
    /// <summary>怪物相关道具</summary>
    ItemType_Monster = 19,
    /// <summary>贝鲁兹（业务专有道具）</summary>
    ItemType_Belluz = 20,
    /// <summary>附魔石</summary>
    ItemType_EnchantStone = 21,
    /// <summary>双倍奖励卡</summary>
    ItemType_DoubleAwardCard = 22,
    /// <summary>宾果号码道具</summary>
    ItemType_BingoNumber = 23,
    /// <summary>特殊道具</summary>
    ItemType_SpecialItem = 24,
    // 注意：25号枚举空缺
    /// <summary>聊天框</summary>
    ItemType_ChatFrame = 26,
    /// <summary>头像框</summary>
    ItemType_PortraitFrame = 27,

    /// <summary>protobuf内部哨兵值，禁止业务使用，标记int32最小值边界</summary>
    //ItemTypeTab_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
    /// <summary>protobuf内部哨兵值，禁止业务使用，标记int32最大值边界</summary>
    //ItemTypeTab_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
}


public enum ItemBind
{
    kItemBindNo = 0,
    kItemBindIs = 1,
};
public enum TimeLimitType
{
    kTimeLimitType_None = 0,                    //没有时效性类型,永久
    kTimeLimitType_TempalteTime = 1,            //模板时间，不可叠加，可热更
    kTimeLimitType_AddTime = 2,                 //叠加时间类型，不可热更
    kTimeLimitType_DailyActivity = 3,           //下次每日活动结束时销毁，不可热更。
    kTimeLimitType_BackStageActivity = 4,       //后台活动，不在活动中销毁，根据活动开关状态控制，临时关闭会导致道具删除！
    kTimeLimitType_BackStageActivityValid = 5,   //后台活动，不在活动期间不销毁，需要玩家主动回收
    kTimeLimitType_BackStageActivityValid_Extra_Time = 6   //后台活动，不在活动期间不销毁，按照 extra time 判断过期
};

public enum ITEM_SWAP_REASON
{
    ISR_None = 0,
    ISR_Init = 1
};
/// <summary>虚拟物品和项目特殊物品的公共配置 ID。</summary>
public enum ItemEnum 
{
    DEAFULT_CONFIG_ID = 0, ///>策划不填的话配置表里面默认是0
    ZENY = 101,			///> 铜币(2020.01.03 更新词意)
    ROMONEY = 102,      ///> zeny币 (2020.01.03 更新词意)
    DIAMOND = 103,      ///> 钻石
    Coin104 = 104,      ///> 免费钻石
    QQ_POINT = 105,  //QQ点 （暂时只有程序测试直购使用）
    BOLI_COIN = 110,   //跑商用波利币

    EXP = 201,			///> 经验
    JOB_EXP = 202,
    MONSTER_RESEARCH_POINT = 205, // 魔物研究点数

    BOLI_POINT = 301,   ///>波利点数
    VITALITY = 302,     ///>元气值
    DELEGATION = 303,      // 委托证明
    GEM_FRAGMENTS = 304,   // 宝石碎片
    

    GUILD_CONTRIBUTION = 401, // 公会贡献
    PRESTIGE = 402, // 声望

    AREAN_COIN = 501,  //勇气徽章
    BATTLEFIELD_COIN = 502, //战场徽章
    MAGIC_COIN = 503, //魔物硬币
    //9种纹章，纹章的ID必须是连续的
    //注意：添加了纹章ID，同时也需要在GetArmoryItem函数里添加一下
    ARMORY_BEGIN = 601, // ---- 纹章开始
    JIANSHI_ARMORY = 601,
    DAOZEI_ARMORY = 602,
    //SHENGGEJIAOHUI_ARMORY,
    //QISHITUAN_ARMORY,
    YUANDONGSHANGHUI_ARMORY = 605,
    FUSHI_ARMORY = 606,
    //SHANGREN_ARMORY , 
    GONGJIANSHOU_ARMORY = 608,
    MOFASHI_ARMORY = 609,
    // 新增纹章加在这中间，纹章的ID必须是连续的
    ARMORY_END,       // ---- 纹章结束

    ASSIST_POINT = 701, //协同之证
    MERCENARY_TALENT_POINT = 702, //佣兵天赋点

    PASS_CHECK_EXP = 804,   //通行证经验值
    DRYBRANCH = 2033001,    //>> 枯树枝(成就打点)
    /// 血迹树枝
    BLOOD_DRYBRANCH = 2033002,
    VIRTUAL_ITEM_MAX = 1000,
};

public enum ItemChangeReason {
    ITEM_REASON_NONE = 0,
    ITEM_REASON_PICK_UP = 1,
    ITEM_REASON_MOVE_ITEM = 2,
    ITEM_REASON_USE = 3,
    ITEM_REASON_CLEAR_TEMP_BAG = 4,
    ITEM_REASON_JUNK = 5,
    ITEM_REASON_TASK_REMOVE = 6,
    ITEM_REASON_TASK_TAKE = 7,
    ITEM_REASON_TASK_REWARD = 8,
    ITEM_REASON_SKILL_STEAL = 9,
    ITEM_REASON_MVP_FINAL_KILL_REWARD = 10,
    ITEM_REASON_MVP_TEAM_REWARD = 11,
    ITEM_REASON_CHANGE_HAIR = 12,
    ITEM_REASON_APPRAISE_EQUIP = 13,
    ITEM_REASON_CHANGE_EYE = 14,
    ITEM_REASON_BUY_ITEM = 15,              // 普通商店购买导致的物品/货币变更。
    ITEM_REASON_COOKING = 16,
    ITEM_REASON_DUNGEONS_RESULT = 17,
    ITEM_REASON_REVIVE = 18,
    ITEM_REASON_FORGE = 19,
    ITEM_REASON_TASK_EDEN = 20,
    ITEM_REASON_JOB_LEVEL_UPGRADE = 21,
    ITEM_REASON_TRANSFER_PROFESSION = 22,
    ITEM_REASON_GM_CMD = 23,
    ITEM_REASON_AWARD_PACK = 24,
    ITEM_REASON_OPEN_SYSTEM_REWARD = 25,
    ITEM_REASON_USE_BUTTERFLY = 26,
    ITEM_REASON_TRADE_BUY = 27,             // 交易行购买导致的物品/货币变更。
    ITEM_REASON_TRADE_SELL = 28,
    ITEM_REASON_REFINE = 29,
    ITEM_REASON_COLLECT = 30,
    ITEM_REASON_GUILD_CREATE = 31,
    ITEM_REASON_ENCHANT = 32,
    ITEM_REASON_MAIL = 33,
    ITEM_REASON_STALL_REFRESH = 34,
    ITEM_REASON_STALL_DRAW_MONEY = 35,
    ITEM_REASON_STALL_BUY = 36,             // 摆摊购买导致的物品/货币变更。
    ITEM_REASON_STALL_BUY_NUM = 37,         // 批量购买摆摊商品导致的物品/货币变更。
    ITEM_REASON_STALL_SELL_ITEM_DROP_DOWN = 38,
    ITEM_REASON_SELL_ITEM = 39,
    ITEM_REASON_SKILL_COST = 40,
    ITEM_REASON_INSERTCARD = 41,
    ITEM_REASON_REMOVECARD = 42,
    ITEM_REASON_MAKEHOLE = 43,
    ITEM_REASON_MAKEREFORM = 44,
    ITEM_REASON_TASK_REWARD_MAIN = 45,
    ITEM_REASON_TASK_REWARD_BRANCH = 46,
    ITEM_REASON_TASK_REWARD_AISHEN = 47,
    ITEM_REASON_TASK_REWARD_EDEN = 48,
    ITEM_REASON_TASK_REWARD_PROFESSION = 49,
    ITEM_REASON_DAILY_ACTIVITY = 50,
    ITEM_REASON_TURNTABLE_TICKTY = 51,
    ITEM_REASON_TURNTABLE_WABAO = 52,
    ITEM_REASON_GIFT_SEND = 53,
    ITEM_REASON_SEVEN_LOGIN_REWARD = 54,
    ITEM_REASON_COLLECT_GARDEN = 55,
    ITEM_REASON_COLLECT_MINING = 56,
    ITEM_REASON_COLLECT_FOOD = 57,
    ITEM_REASON_COLLECT_MEDICINE = 58,
    ITEM_REASON_COLLECT_DESSERT = 59,
    ITEM_REASON_COLLECT_SMELT = 60,
    ITEM_REASON_COLLECT_FISHING = 61,
    ITEM_REASON_FIVE_REFRESH = 62,
    ITEM_REASON_MVP_JOIN_AWARD = 63,
    ITEM_REASON_EDEN_TICKET = 64,
    ITEM_REASON_COLLECT_SMELT_WEAPON = 65,
    ITEM_REASON_COLLECT_SMELT_DEFEND = 66,
    ITEM_REASON_COLLECT_SMELT_ACC = 67,
    ITEM_REASON_ATTR_CLEAR = 68,
    ITEM_REASON_HYMN_TRIAL = 69,
    ITEM_REASON_DIR_TELEPORT = 70,
    ITEM_REASON_EQUIP_COMPOUND = 71,
    ITEM_REASON_GUILD_BUILD = 72,
    ITEM_REASON_MATERIAL_MECHANT = 73,
    ITEM_REASON_ENCHANT_REBORN = 74,
    ITEM_REASON_BOLI_AWARD = 75,
    ITEM_REASON_GUILD_ITEM_EXCHANGE = 76,
    ITEM_REASON_GUILD_WELFARE = 77,
    ITEM_REASON_CARD_RECYCLE = 78,
    ITEM_REASON_GUILD_DINNER_TASK_FINISH_SCENE_REWARD = 80,
    ITEM_REASON_GUILD_DINNER_EAT_DISH = 81,
    ITEM_REASON_GUILD_DINNER_SCENE_REWARD = 82,
    ITEM_REASON_GUILD_QUIT_FREEZE = 83,
    ITEM_REASON_GUILD_ENTER_FREEZE = 84,
    ITEM_REASON_WORLD_PVE_BASE = 85,
    ITEM_REASON_WORLD_PVE_ADDITIONAL = 86,
    ITEM_REASON_ORNAMENT_RECYCLE = 87,
    ITEM_REASON_USE_DEVICE = 88,
    ITEM_REASON_DEVICE_MAKE = 89,
    ITEM_REASON_REFINE_TRANSFER = 90,
    ITEM_REASON_REFINE_UNLOCK_SEAL = 91,
    ITEM_REASON_TASK_ADVENTURE = 92,
    ITEM_REASON_COOK_DUNGEONS = 93,
    ITEM_REASON_CAT_TRADE_REWARD = 94,
    ITEM_REASON_CAT_TRADE_SELL_GOODS = 95,
    ITEM_REASON_MEDAL_ACTIVE = 96,
    ITEM_REASON_MEDAL_UPGRADE = 97,
    ITEM_REASON_MEDAL_RESET = 98,
    ITEM_REASON_TOWER_RESULT = 99,
    ITEM_REASON_BATTLE_RESULT = 100,
    ITEM_REASON_THEME_RESULT = 101,
    ITEM_REASON_CARD_DRAW = 102,
    ITEM_REASON_ORNAMENT_DRAW = 103,
    ITEM_REASON_MINI_JOIN_AWARD = 104,
    ITEM_REASON_PLATFORM_RESULT = 105,
    ITEM_REASON_HERO_CHALLENGE_RESULT = 106,
    ITEM_REASON_PICK_UP_EXP = 107,
    ITEM_REASON_DROP_PUBLIC = 108,
    ITEM_REASON_DROP_PRIVATE = 109,
    ITEM_REASON_GROUP_AWARD = 110,
    ITEM_REASON_IDIP = 111,
    ITEM_REASON_GUILD_SEND_MAIL = 112,
    ITEM_REASON_ROLL_POINT = 113,
    ITEM_REASON_FLOP = 114,
    ITEM_REASON_KILL_MINI = 115,
    ITEM_REASON_POSTCARD_AWARD = 116,
    ITEM_REASON_GUILD_CRYSTAL_QUICK_UPGRADE = 120,
    ITEM_REASON_GUILD_CRYSTAL_GIVE_ENERGY = 121,
    ITEM_REASON_GUILD_CRYSTAL_PRAY = 122,
    ITEM_REASON_DELEGATE_COST = 123,
    ITEM_REASON_DELEGATE_RETURN = 124,
    ITEM_REASON_DELEGATE_UPPER_LIMIT = 125,
    ITEM_REASON_DELEGATE_RESET = 126,
    ITEM_REASON_DELEGATE_ACTIVE_AWARD = 127,
    ITEM_REASON_ASSIST = 128,
    ITEM_REASON_ASSIST_SPECIAL = 129,
    ITEM_REASON_THIRTY_SIGN_IN = 130,
    ITEM_REASON_ACHIEVEMENT_ITEM = 131,
    ITEM_REASON_ACHIEVEMENT_POINT = 132,
    ITEM_REASON_DUNGEON_COST = 133,
    ITEM_REASON_ACTIVE_JUNK = 134,
    ITEM_REASON_DUNGEON_WEEK = 135,
    ITEM_REASON_COBBLESTONE = 136,
    ITEM_REASON_MAKE_STONE = 137,
    ITEM_REASON_SERVER_UNSYNC = 138,
    ITEM_REASON_GUILD_HUNT_FINAL_REWARD = 140,
    ITEM_REASON_GUILD_HUNT_DUNGEONS = 141,
    ITEM_REASON_MAZE_DUNGEONS = 142,
    ITEM_REASON_SEND_RED_ENEVLOPE = 143,
    ITEM_REASON_GRAB_RED_ENEVLOPE = 144,
    ITEM_REASON_MERCHANT_BUY = 145,         // 行商购买导致的物品/货币变更。
    ITEM_REASON_MERCHANT_SELL = 146,
    ITEM_REASON_MERCHANT_CLEAR = 147,
    ITEM_REASON_MERCHANT_INIT = 148,
    ITEM_REASON_MERCHANT_EVENT_BUY = 149,   // 行商活动购买导致的物品/货币变更。
    ITEM_REASON_LEVEL_GIFT = 150,
    ITEM_REASON_LIMITED_TIME_OFFER = 151,
    ITEM_REASON_BUY_MALL_ITEM = 152,        // 商城购买导致的物品/货币变更。
    ITEM_REASON_PAY = 153,                  // 充值支付到账导致的物品/货币变更。
    ITEM_REASON_DUNGEONS_AWARD = 154,
    ITEM_REASON_FASHION_EVA_JOIN = 155,
    ITEM_REASON_DELEGATE_DARW_AWARD = 156,
    ITEM_REASON_THEME_PARTY_INVITATION = 157,
    ITEM_REASON_THEME_PARTY_LOTTERY = 158,
    ITEM_REASON_OFFLINE_ITEM_DELETE = 159,
    ITEM_REASON_THEME_PARTY_EXP = 160,
    ITEM_REASON_GUILD_DINNER_PHOTO = 161,
    ITEM_REASON_CREAM_MELEE_WINNER = 162,
    ITEM_REASON_CREAM_MELEE_WATCH = 163,
    ITEM_REASON_BATTLE_STATISTICS = 164,
    ITEM_REASON_GUILD_DINNER_BOX = 165,
    ITEM_REASON_BIG_WORLD_FRUIT = 166,
    ITEM_REASON_THEME_PARTY_DANCE = 167,
    ITEM_REASON_GUILD_PACK = 168,
    ITEM_REASON_MULTI_TALENT = 169,
    ITEM_REASON_SKILL_RESET = 170,
    ITEM_REASON_COLLECT_DIG_TREASURE = 171,
    ITEM_REASON_GUILD_AUCTION = 172,
    ITEM_REASON_FASHION_COUNT_AWARD = 173,
    ITEM_REASON_TAKE_OFF_EQUIP = 174,
    ITEM_REASON_WEAR_EQUIP = 175,
    ITEM_REASON_LEVEL_GIFT_BUY = 176,
    ITEM_REASON_TOWER_DEFENSE_DUNGEON = 177,
    ITEM_REASON_VEHICLE = 178,
    ITEM_REASON_DEVELOP_VEHICLE = 179,
    ITEM_REASON_UPGRADE_MERCENARY_EQUIP = 180,
    ITEM_REASON_ADVANCE_MERCENARY_EQUIP = 181,
    ITEM_REASON_UPGRADE_MERCENARY_TALENT = 182,
    ITEM_REASON_STRENGTHEN_MERCENARY_TALENT = 183,
    ITEM_REASON_RESET_MERCENARY_TALENT = 184,
    ITEM_REASON_UPGRADE_MERCENARY = 185,
    ITEM_REASON_STUDY_MERCENARY_TALENT = 186,
    ITEM_REASON_TLOG_LIFESKILL_DEBUG = 187,
    ITEM_REASON_TRADE_RESELL_ITEM = 188,
    ITEM_REASON_GUILD_KICK_OUT_ROLE = 189,
    ITEM_REASON_ENCHANT_REBORN_PERFECT = 190,
    ITEM_REASON_ENCHANT_INHERIT = 191,
    ITEM_REASON_THEME_PARTY_DANCE_RIGHT = 192,
    ITEM_REASON_TAKE_OFF_MULTI_EQUIP = 193,
    ITEM_REASON_WEAR_MULTI_EQUIP = 194,
    ITEM_REASON_NPC_PRESENT = 195,
    ITEM_REASON_THEME_PARTY_JOIN_AWARD = 196,
    ITEM_REASON_STALL_SELL = 197,
    ITEM_REASON_OPEN_CHAMPAGNE = 198,
    ITEM_REASON_DINNER_COMPETITION = 199,
    ITEM_REASON_PAY_FAILD = 200,
    ITEM_REASON_GUILD_DINNER_CHAMPAGNE_EXP = 201,
    ITEM_REASON_GUILD_MATCH = 202,
    ITEM_REASON_ASSIST_MENGXIN = 203,
    ITEM_REASON_ASSIST_HUILIU = 204,
    ITEM_REASON_ASSIST_XIAOHAO = 205,
    ITEM_REASON_FASHIONTICKET = 206,
    ITEM_REASON_BATTLE_ASSIST_RESULT = 207,
    ITEM_REASON_MONTH_CARD = 208,
    ITEM_REASON_BUY_GIFT_PACK = 209,        // 购买礼包导致的物品/货币变更。
    ITEM_REASON_PICK_FREE_SMALL_GIFT_PCAK = 210,
    ITEM_REASON_THEMESTORY_RESULT = 211,
    ITEM_REASON_COOK_DUNGEONS_WEEKEND = 212,
    ITEM_REASON_TOWER_DEFENSE_WEEKAWARD = 213,
    ITEM_REASON_BLACK_MARKET_SELL = 214,
    ITEM_REASON_AUCTION_SUCCESS = 215,
    ITEM_REASON_AUCTION_BIB_FAILD = 216,
    ITEM_REASON_AUCTION_CANCEL_AUTO_BIB = 217,
    ITEM_REASON_AUCTION_BIB_BE_EXCEED = 218,
    ITEM_REASON_AUCTION_BIB = 219,
    ITEM_REASON_OUTSIDE_BILL = 220,
    ITEM_REASON_EDEN_LUCK = 221,
    ITEM_REASON_EDEN_PROFESSION = 222,
    ITEM_REASON_EQUIP_DRAW = 223,
    ITEM_REASON_EQUIP_RECYCLE = 224,
    ITEM_REASHON_YAHAHA_AWARD = 225,
    ITEM_REASON_EXP_BLESS = 226,
    ITEM_REASON_EXP_HEALTH = 227,
    ITEM_REASON_COLLECT_FOOD_FAILURE = 228,
    ITEM_REASON_COLLECT_FOOD_BIG_SUCCESS = 229,
    ITEM_REASON_COLLECT_MEDICINE_FAILURE = 230,
    ITEM_REASON_COLLECT_MEDICINE_BIG_SUCCESS = 231,
    ITEM_REASON_COLLECT_DESSERT_FAILURE = 232,
    ITEM_REASON_COLLECT_DESSERT_BIG_SUCCESS = 233,
    ITEM_REASON_COLLECT_SMELT_WEAPON_FAILURE = 234,
    ITEM_REASON_COLLECT_SMELT_WEAPON_BIG_SUCCESS = 235,
    ITEM_REASON_COLLECT_SMELT_DEFEND_FAILURE = 236,
    ITEM_REASON_COLLECT_SMELT_DEFEND_BIG_SUCCESS = 237,
    ITEM_REASON_COLLECT_SMELT_ACC_FAILURE = 238,
    ITEM_REASON_COLLECT_SMELT_ACC_BIG_SUCCESS = 239,
    ITEM_REASON_COLLECT_FOOD_FUSION = 240,
    ITEM_REASON_COLLECT_MEDICINE_FUSION = 241,
    ITEM_REASON_LIFE_SKILL_UPGRADE = 242,
    ITEM_REASON_UNSEAL_CARD = 243,
    ITEM_REASON_MSASK = 244,
    ITEM_REASON_PAPER_SUCC = 245,
    ITEM_REASON_MAGIC_PAPER_GRAB = 246,
    ITEM_REASON_RESET_WHEEL = 247,
    ITEM_REASON_CHOOSE_WHEEL_SKILL = 248,
    ITEM_REASON_COMPOSITE_WHEEL = 249,
    ITEM_REASON_MAINTEANCE_WHEEL = 250,
    ITEM_REASON_MONSTER_MANUAL = 251,
    ITEM_REASON_EQUIP_INHERIT = 252,
    ITEM_REASON_QUIT_GIULD_REDUCE_ITEM = 253,
    ITEM_REASON_GUILD_ORGANIZA_PERSONAL_AWARD = 254,
    ITEM_REASON_TREASURE_HUNT_FOOTPRINT = 255,
    ITEM_REASON_TREASURE_HUNT_BOX = 256,
    ITEM_REASON_HUIYUAN_CARD = 257,
    ITEM_REASON_HUIYUAN_CARD_CHANGE = 258,
    ITEM_REASON_PRESTIGE_BOX = 259,
    ITEM_REASON_UNLOCK_HAIR = 260,
    ITEM_REASON_UNLOCK_EYES = 261,
    ITEM_REASON_CHAT = 262,
    ITEM_REASON_DIAMOND_SYNC = 263,
    ITEM_REASON_SPECIAL_SUPPLY = 264,
    ITEM_REASON_SPECIAL_SUPPLY_REDICE = 265,
    ITEM_REASON_SPECIAL_SUPPLY_QUICK_DICE = 266,
    ITEM_REASON_ACT_MONTH_CARD = 267,
    ITEM_REASON_MAIL_GIVE_PAYMEN = 268,
    ITEM_REASON_TOWER_JUMP = 269,
    ITEM_REASON_BINGO_LIGHT = 270,
    ITEM_REASON_SPECIAL_ITEM_EXTRA = 271,
    ITEM_REASON_CONSUME_SPECIAL_ITEM = 272,
    ITEM_REASON_MODIFY_ACTIVE = 273,
    ITEM_REASON_HEALTH_QUICKLY = 274,
    ITEM_REASON_DABAO_CANDY = 275,
    ITEM_REASON_PAY_AWARD = 276,            // 充值活动奖励导致的物品/货币变更。
    ITEM_REASON_FRESH_MALL_CARDS = 277,     // 刷新商城商品导致的物品/货币变更。
    ITEM_REASON_TEAMLEADER_EXTRA_AWARD = 278,
    ITEM_REASON_TEAMLEADER_EXTRA_BIG_AWARD = 279,
    ITEM_REASON_AUCTION_RETRY = 280,
    ITEM_REASON_EXTRA_CARD_DROP = 281,
    ITEM_REASON_EXCHANGE_MONEY = 282,
    ITEM_REASON_RETURN_TASK_PRIZE = 283,
    ITEM_REASON_RETURN_LOGIN_PRIZE = 284,
    ITEM_REASON_MALL_MANUAL_REFRESH = 285,
    ITEM_REASON_GMT_NORMAL = 286,
    ITEM_REASON_GMT_REFUND = 287,
    ITEM_REASON_RETURN_WELCOME_PRIZE = 288,
    ITEM_REASON_TAGNEW_LEVELGIFT = 289,
    ITEM_REASON_WARRIOR_RECRUIT = 290,
    ITEM_REASON_TASK_RECRUIT = 291,
    ITEM_REASON_BAG_MOVE_TO_WAREHOUSE = 292,
    ITEM_REASON_WAREHOUSE_MOVE_TO_BAG = 293,
    ITEM_REASON_BAG_MOVE_TO_CART = 294,
    ITEM_REASON_CART_MOVE_TO_BAG = 295,
    ITEM_REASON_CAT_TRADE_SELL_EXTRA = 296,
    ITEM_REASON_COVENANT_GUIDE_TASK = 297,
    ITEM_REASON_COVENANT_REWARD = 298,
    ITEM_REASON_MIDAUTUMN_DRAW = 299,
    ITEM_REASON_MIDAUTUMN_EXTRA_AWARD = 300,
    ITEM_REASON_ITEM_RECYCLE = 301,
    ITEM_REASON_COMPOSE_ITEM_ADD = 302,
    ITEM_REASON_COMPOSE_ITEM_REDUCE = 303,
    ITEM_REASON_QIU_XI_JIE = 304,
    ITEM_REASON_UNLOCK_EMOJI = 305,
    ITEM_REASON_GVG_AWARD = 306,
    ITEM_REASON_GVG_CITY_DONATE = 307,
    ITEM_REASON_GVG_GIVE_SUPPLIES = 308,
    ITEM_REASON_GVG_BOX_PERSONAL = 309,
    ITEM_REASON_BUY_PASS_CHECK = 310,
    ITEM_REASON_PASS_CHECK_AWARD = 311,
    ITEM_REASON_PASS_CHECK_TASK = 312,
    ITEM_REASON_BUY_ITEM_BY_MONEY_FREE_GIFT = 313,
    ITEM_REASON_LEVLE_GIFT = 314,
    ITEM_REASON_HALLOWEEN = 315,
    ITEM_REASON_HALLOWEEN_EXP = 316,
    ITEM_REASON_CALL_REGRESS = 317,
    ITEM_REASON_SIGNACTIVITY = 318,
    ITEM_REASON_GUILD_AUCTION_RECOVER = 319,
    ITEM_REASON_BUY_PASS_CHECK_LEVEL = 320,
    ITEM_REASON_GVG_GUILD_FIRE_EXP = 321,
    ITEM_REASON_DELEGATE_DEPOSIT = 322,
    ITEM_REASON_SNOW_BOLI_SUPPLY = 323,
    ITEM_REASON_ISS_AWARD = 324,
    ITEM_REASON_ENCHANT_ACTIVITY = 325,
    ITEM_REASON_CRUSADER_AWARD = 326,
    ITEM_REASON_REFORM_REBORN = 327,
    ITEM_REASON_SNOWBALL_FIGHT = 328,
    ITEM_REASON_DIAMOND_TO_ZENY = 329,
    ITEM_REASON_DIAMOND_TO_ROMONEY = 330,
    ITEM_REASON_ABANDON_TASK_ITEM = 331,
    ITEM_REASON_HELM_RACING_ACTIVITY = 332,
    ITEM_REASON_REDUCE_DEVICE_DURABILITY = 333,
    ITEM_REASON_Belluz_Change_Multi_Talent = 334,
    ITEM_CHANGE_LUCKY_KITCHEN = 335,
    ITEM_REASON_COLORING = 336,
    ITEM_REASON_SUIT_BOOK_AWARD = 337,
    ITEM_REASON_INDUCTION_NEW = 338,
    ITEM_REASON_INDUCTION_CHANGE = 339,
    ITEM_REASON_INDUCTION_REDUCE = 340,
    //ItemChangeReason_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
    //ItemChangeReason_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};

public enum SignBit 
{
    /// 第0位表示物品是否绑定1是绑定，0是不绑定
    BindBit = 0,            
    /// 第一位表示是否损坏，0表示没有损坏，1表示损坏。
    BrokenBit = 1,   
    /// 附魔是否已提炼，0未提炼，1已提炼
    RebornBit = 2,      
    /// 第二位表示 是否是商会买来的
    BusinessBit = 3,      
    /// 第三位标记 是否是拍卖买来
    AuctionBit = 4,   
    /// 到期后是否保留
    LifeEndSurvivalBit = 5,   
    /// 是否激活 0代表不激活，1代表激活
    ActiveBit  = 6,  
    /// 是否是限时道具
    TimingItem = 7,  
    /// 重连是否需要通知(弃用)
    NeedReconnect = 8,
    /// 改造提炼
    ReformRebornBit = 9, 
    /// 感应状态位
    InductionBit = 10
};

public enum ItemSign 
{
    //位运算优先级很低，一定要加括号！
    IsNoSign = 0,
    IsItemSignBind = (1 << SignBit.BindBit),
    IsBroken = (1 << SignBit.BrokenBit),
    IsReborn = (1 << SignBit.RebornBit),
    IsBusiness = (1 << SignBit.BusinessBit),
    IsAuction = (1 << SignBit.AuctionBit),
    IsLifeEndSurvivalBit = (1 << SignBit.LifeEndSurvivalBit),
    IsActive = (1 << SignBit.ActiveBit),
    IsTimingItem = ( 1 << SignBit.TimingItem),
    IsReconnectNtf = (1 << SignBit.NeedReconnect),
    IsReformReborn = (1 << SignBit.ReformRebornBit),
    IsInductionBit = (1 << SignBit.InductionBit),
};
public struct IdipParam
{
    string serial_num; // IDIP 请求流水号。
    int source_id;   // IDIP 来源标识。
    string cmd;        // IDIP 命令名称。
};

