
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class CountInfo : Luban.BeanBase
{
    public CountInfo(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Action = _buf.ReadInt();
        GoodsId = _buf.ReadInt();
        Name = _buf.ReadString();
        RefreshType = _buf.ReadInt();
        RefreshNum = _buf.ReadInt();
        Limit = _buf.ReadInt();
        ActiveRefresh = _buf.ReadInt();
        TellClient = _buf.ReadInt();
    }

    public static CountInfo DeserializeCountInfo(ByteBuf _buf)
    {
        return new CountInfo(_buf);
    }

    /// <summary>
    /// 配置排序 ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 计数行为类型（1商城购买，2副本进入，3副本购买）
    /// </summary>
    public readonly int Action;
    /// <summary>
    /// 业务对象 ID（商城为 GoodsId，副本为 DungeonId）
    /// </summary>
    public readonly int GoodsId;
    /// <summary>
    /// 计数项名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 刷新类型（0不刷新，1每日0点，2每日5点，3每周一0点，4每周一5点）
    /// </summary>
    public readonly int RefreshType;
    /// <summary>
    /// 刷新时增加次数
    /// </summary>
    public readonly int RefreshNum;
    /// <summary>
    /// 次数上限
    /// </summary>
    public readonly int Limit;
    /// <summary>
    /// 是否允许主动刷新（0否，1是）
    /// </summary>
    public readonly int ActiveRefresh;
    /// <summary>
    /// 是否通知客户端（0否，1是）
    /// </summary>
    public readonly int TellClient;
   
    public const int __ID__ = -939578819;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Action:" + Action + ","
        + "GoodsId:" + GoodsId + ","
        + "Name:" + Name + ","
        + "RefreshType:" + RefreshType + ","
        + "RefreshNum:" + RefreshNum + ","
        + "Limit:" + Limit + ","
        + "ActiveRefresh:" + ActiveRefresh + ","
        + "TellClient:" + TellClient + ","
        + "}";
    }
}
}

