
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class EquipInfo : Luban.BeanBase
{
    public EquipInfo(ByteBuf _buf) 
    {
        ItemTypeId = _buf.ReadInt();
        ItemMainType = _buf.ReadInt();
        ItemSubType = _buf.ReadInt();
        EquipType = _buf.ReadInt();
        EquipName = _buf.ReadString();
        Icon = _buf.ReadString();
        Attribute = _buf.ReadString();
        Desc = _buf.ReadString();
        NeedLevel = _buf.ReadInt();
        Source = _buf.ReadString();
        SellPrice = _buf.ReadInt();
        SellCurrencyType = _buf.ReadInt();
        Job = _buf.ReadInt();
        BCanBeStacked = _buf.ReadInt();
        GeneId0 = _buf.ReadInt();
        GeneId1 = _buf.ReadInt();
        GeneId2 = _buf.ReadInt();
        GeneId3 = _buf.ReadInt();
        GeneId4 = _buf.ReadInt();
        GeneId5 = _buf.ReadInt();
        GeneValue0 = _buf.ReadInt();
        GeneValue1 = _buf.ReadInt();
        GeneValue2 = _buf.ReadInt();
        GeneValue3 = _buf.ReadInt();
        GeneValue4 = _buf.ReadInt();
        GeneValue5 = _buf.ReadInt();
        CanStrengthen = _buf.ReadInt();
        MaxStrengthenLevel = _buf.ReadInt();
        MaxGemLevel = _buf.ReadInt();
        GemSlotCount = _buf.ReadInt();
        Des = _buf.ReadString();
    }

    public static EquipInfo DeserializeEquipInfo(ByteBuf _buf)
    {
        return new EquipInfo(_buf);
    }

    /// <summary>
    /// 物品配置ID
    /// </summary>
    public readonly int ItemTypeId;
    /// <summary>
    /// 物品大类（1普通物品，2装备）
    /// </summary>
    public readonly int ItemMainType;
    /// <summary>
    /// 物品小类（装备统一为-1）
    /// </summary>
    public readonly int ItemSubType;
    /// <summary>
    /// 装备类别
    /// </summary>
    public readonly int EquipType;
    /// <summary>
    /// 装备名称
    /// </summary>
    public readonly string EquipName;
    /// <summary>
    /// 物品图标
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 物品属性
    /// </summary>
    public readonly string Attribute;
    /// <summary>
    /// 物品简介
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 使用物品所需等级
    /// </summary>
    public readonly int NeedLevel;
    /// <summary>
    /// 物品来源
    /// </summary>
    public readonly string Source;
    /// <summary>
    /// 出售价格
    /// </summary>
    public readonly int SellPrice;
    /// <summary>
    /// 出售货币类型
    /// </summary>
    public readonly int SellCurrencyType;
    /// <summary>
    /// 所需职业
    /// </summary>
    public readonly int Job;
    /// <summary>
    /// 是否可以叠加
    /// </summary>
    public readonly int BCanBeStacked;
    /// <summary>
    /// 属性槽位0 Gene ID
    /// </summary>
    public readonly int GeneId0;
    /// <summary>
    /// 属性槽位1 Gene ID
    /// </summary>
    public readonly int GeneId1;
    /// <summary>
    /// 属性槽位2 Gene ID
    /// </summary>
    public readonly int GeneId2;
    /// <summary>
    /// 属性槽位3 Gene ID
    /// </summary>
    public readonly int GeneId3;
    /// <summary>
    /// 属性槽位4 Gene ID
    /// </summary>
    public readonly int GeneId4;
    /// <summary>
    /// 属性槽位5 Gene ID
    /// </summary>
    public readonly int GeneId5;
    /// <summary>
    /// 属性槽位0数值
    /// </summary>
    public readonly int GeneValue0;
    /// <summary>
    /// 属性槽位1数值
    /// </summary>
    public readonly int GeneValue1;
    /// <summary>
    /// 属性槽位2数值
    /// </summary>
    public readonly int GeneValue2;
    /// <summary>
    /// 属性槽位3数值
    /// </summary>
    public readonly int GeneValue3;
    /// <summary>
    /// 属性槽位4数值
    /// </summary>
    public readonly int GeneValue4;
    /// <summary>
    /// 属性槽位5数值
    /// </summary>
    public readonly int GeneValue5;
    /// <summary>
    /// 是否可以强化(0否,1是)
    /// </summary>
    public readonly int CanStrengthen;
    /// <summary>
    /// 强化最高等级
    /// </summary>
    public readonly int MaxStrengthenLevel;
    /// <summary>
    /// 可镶嵌宝石最高等级
    /// </summary>
    public readonly int MaxGemLevel;
    /// <summary>
    /// 宝石孔数量
    /// </summary>
    public readonly int GemSlotCount;
    /// <summary>
    /// 装备简介
    /// </summary>
    public readonly string Des;
   
    public const int __ID__ = -1215706914;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ItemTypeId:" + ItemTypeId + ","
        + "ItemMainType:" + ItemMainType + ","
        + "ItemSubType:" + ItemSubType + ","
        + "EquipType:" + EquipType + ","
        + "EquipName:" + EquipName + ","
        + "Icon:" + Icon + ","
        + "Attribute:" + Attribute + ","
        + "Desc:" + Desc + ","
        + "NeedLevel:" + NeedLevel + ","
        + "Source:" + Source + ","
        + "SellPrice:" + SellPrice + ","
        + "SellCurrencyType:" + SellCurrencyType + ","
        + "Job:" + Job + ","
        + "bCanBeStacked:" + BCanBeStacked + ","
        + "GeneId0:" + GeneId0 + ","
        + "GeneId1:" + GeneId1 + ","
        + "GeneId2:" + GeneId2 + ","
        + "GeneId3:" + GeneId3 + ","
        + "GeneId4:" + GeneId4 + ","
        + "GeneId5:" + GeneId5 + ","
        + "GeneValue0:" + GeneValue0 + ","
        + "GeneValue1:" + GeneValue1 + ","
        + "GeneValue2:" + GeneValue2 + ","
        + "GeneValue3:" + GeneValue3 + ","
        + "GeneValue4:" + GeneValue4 + ","
        + "GeneValue5:" + GeneValue5 + ","
        + "CanStrengthen:" + CanStrengthen + ","
        + "MaxStrengthenLevel:" + MaxStrengthenLevel + ","
        + "MaxGemLevel:" + MaxGemLevel + ","
        + "GemSlotCount:" + GemSlotCount + ","
        + "Des:" + Des + ","
        + "}";
    }
}
}

