
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class Gene : Luban.BeanBase
{
    public Gene(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        EffectDesc = _buf.ReadString();
        Scenario = _buf.ReadInt();
        ValueType = _buf.ReadInt();
        AttachGeneId0 = _buf.ReadInt();
        AttachGeneId1 = _buf.ReadInt();
        AttachGeneId2 = _buf.ReadInt();
        AttachGeneId3 = _buf.ReadInt();
        AttachGeneId4 = _buf.ReadInt();
        IsStack = _buf.ReadInt();
        BuffTime = _buf.ReadInt();
    }

    public static Gene DeserializeGene(ByteBuf _buf)
    {
        return new Gene(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 属性效果说明
    /// </summary>
    public readonly string EffectDesc;
    /// <summary>
    /// 0全局，1副本，2pvp场所
    /// </summary>
    public readonly int Scenario;
    /// <summary>
    /// 0是代表数值，1代表百分比
    /// </summary>
    public readonly int ValueType;
    /// <summary>
    /// 基因组合0
    /// </summary>
    public readonly int AttachGeneId0;
    /// <summary>
    /// 基因组合2
    /// </summary>
    public readonly int AttachGeneId1;
    /// <summary>
    /// 基因组合3
    /// </summary>
    public readonly int AttachGeneId2;
    /// <summary>
    /// 基因组合4
    /// </summary>
    public readonly int AttachGeneId3;
    /// <summary>
    /// 基因组合5
    /// </summary>
    public readonly int AttachGeneId4;
    /// <summary>
    /// 是否可以叠加,0可以叠加，1不可以叠加
    /// </summary>
    public readonly int IsStack;
    /// <summary>
    /// 单位秒，0为常驻buff
    /// </summary>
    public readonly int BuffTime;
   
    public const int __ID__ = 2215733;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "EffectDesc:" + EffectDesc + ","
        + "Scenario:" + Scenario + ","
        + "ValueType:" + ValueType + ","
        + "AttachGeneId0:" + AttachGeneId0 + ","
        + "AttachGeneId1:" + AttachGeneId1 + ","
        + "AttachGeneId2:" + AttachGeneId2 + ","
        + "AttachGeneId3:" + AttachGeneId3 + ","
        + "AttachGeneId4:" + AttachGeneId4 + ","
        + "IsStack:" + IsStack + ","
        + "buffTime:" + BuffTime + ","
        + "}";
    }
}
}

