
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class ItemInfo : Luban.BeanBase
{
    public ItemInfo(ByteBuf _buf) 
    {
        ItemTypeId = _buf.ReadInt();
        ItemMainType = _buf.ReadInt();
        ItemSubType = _buf.ReadInt();
        Quality = _buf.ReadInt();
        Icon = _buf.ReadString();
        Name = _buf.ReadString();
        Attribute = _buf.ReadString();
        Desc = _buf.ReadString();
        UseScene = _buf.ReadInt();
        NeedLevel = _buf.ReadInt();
        BCanBind = _buf.ReadInt();
        Source = _buf.ReadString();
        SellPrice = _buf.ReadInt();
        SellCurrencyType = _buf.ReadInt();
        CanStack = _buf.ReadInt();
        GeneId0 = _buf.ReadInt();
        GeneId1 = _buf.ReadInt();
        GeneId2 = _buf.ReadInt();
        GeneId3 = _buf.ReadInt();
        GeneId4 = _buf.ReadInt();
        GeneValue0 = _buf.ReadInt();
        GeneValue1 = _buf.ReadInt();
        GeneValue2 = _buf.ReadInt();
        GeneValue3 = _buf.ReadInt();
        GeneValue4 = _buf.ReadInt();
    }

    public static ItemInfo DeserializeItemInfo(ByteBuf _buf)
    {
        return new ItemInfo(_buf);
    }

    /// <summary>
    /// 物品配置唯一ID
    /// </summary>
    public readonly int ItemTypeId;
    /// <summary>
    /// 物品大类（1普通物品，2装备）
    /// </summary>
    public readonly int ItemMainType;
    /// <summary>
    /// 物品小类别
    /// </summary>
    public readonly int ItemSubType;
    /// <summary>
    /// 品级
    /// </summary>
    public readonly int Quality;
    /// <summary>
    /// 物品图标
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 物品简介
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 物品属性
    /// </summary>
    public readonly string Attribute;
    /// <summary>
    /// 物品简介
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 使用场景
    /// </summary>
    public readonly int UseScene;
    /// <summary>
    /// 使用物品所需等级
    /// </summary>
    public readonly int NeedLevel;
    /// <summary>
    /// 是否绑定
    /// </summary>
    public readonly int BCanBind;
    /// <summary>
    /// 物品来源
    /// </summary>
    public readonly string Source;
    /// <summary>
    /// 出售价格
    /// </summary>
    public readonly int SellPrice;
    /// <summary>
    /// 出售货币类型
    /// </summary>
    public readonly int SellCurrencyType;
    /// <summary>
    /// 是否可以叠加(0否,1是)
    /// </summary>
    public readonly int CanStack;
    /// <summary>
    /// 词条0 ID(0表示无)
    /// </summary>
    public readonly int GeneId0;
    /// <summary>
    /// 词条1 ID(0表示无)
    /// </summary>
    public readonly int GeneId1;
    /// <summary>
    /// 词条2 ID(0表示无)
    /// </summary>
    public readonly int GeneId2;
    /// <summary>
    /// 词条3 ID(0表示无)
    /// </summary>
    public readonly int GeneId3;
    /// <summary>
    /// 词条4 ID(0表示无)
    /// </summary>
    public readonly int GeneId4;
    /// <summary>
    /// 词条0数值
    /// </summary>
    public readonly int GeneValue0;
    /// <summary>
    /// 词条1数值
    /// </summary>
    public readonly int GeneValue1;
    /// <summary>
    /// 词条2数值
    /// </summary>
    public readonly int GeneValue2;
    /// <summary>
    /// 词条3数值
    /// </summary>
    public readonly int GeneValue3;
    /// <summary>
    /// 词条4数值
    /// </summary>
    public readonly int GeneValue4;
   
    public const int __ID__ = 1241839233;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ItemTypeId:" + ItemTypeId + ","
        + "ItemMainType:" + ItemMainType + ","
        + "ItemSubType:" + ItemSubType + ","
        + "Quality:" + Quality + ","
        + "Icon:" + Icon + ","
        + "Name:" + Name + ","
        + "Attribute:" + Attribute + ","
        + "Desc:" + Desc + ","
        + "UseScene:" + UseScene + ","
        + "NeedLevel:" + NeedLevel + ","
        + "bCanBind:" + BCanBind + ","
        + "Source:" + Source + ","
        + "SellPrice:" + SellPrice + ","
        + "SellCurrencyType:" + SellCurrencyType + ","
        + "CanStack:" + CanStack + ","
        + "GeneId0:" + GeneId0 + ","
        + "GeneId1:" + GeneId1 + ","
        + "GeneId2:" + GeneId2 + ","
        + "GeneId3:" + GeneId3 + ","
        + "GeneId4:" + GeneId4 + ","
        + "GeneValue0:" + GeneValue0 + ","
        + "GeneValue1:" + GeneValue1 + ","
        + "GeneValue2:" + GeneValue2 + ","
        + "GeneValue3:" + GeneValue3 + ","
        + "GeneValue4:" + GeneValue4 + ","
        + "}";
    }
}
}

