
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class KnapsackInfo : Luban.BeanBase
{
    public KnapsackInfo(ByteBuf _buf) 
    {
        KnapsackType = _buf.ReadInt();
        DefaultGridCount = _buf.ReadInt();
    }

    public static KnapsackInfo DeserializeKnapsackInfo(ByteBuf _buf)
    {
        return new KnapsackInfo(_buf);
    }

    /// <summary>
    /// 背包类型（0角色背包，1角色武器背包，2角色消耗品背包，3角色材料背包）
    /// </summary>
    public readonly int KnapsackType;
    /// <summary>
    /// 默认开启格子数
    /// </summary>
    public readonly int DefaultGridCount;
   
    public const int __ID__ = 225360886;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "KnapsackType:" + KnapsackType + ","
        + "DefaultGridCount:" + DefaultGridCount + ","
        + "}";
    }
}
}

