
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class NpcInfo : Luban.BeanBase
{
    public NpcInfo(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        PrefabPath = _buf.ReadString();
        Pos = _buf.ReadString();
        Tyep = _buf.ReadInt();
        ItemList = _buf.ReadString();
        Think = _buf.ReadString();
        Talk = _buf.ReadString();
        Mapid = _buf.ReadInt();
    }

    public static NpcInfo DeserializeNpcInfo(ByteBuf _buf)
    {
        return new NpcInfo(_buf);
    }

    /// <summary>
    /// NPC_Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// NPC名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 资源路劲
    /// </summary>
    public readonly string PrefabPath;
    /// <summary>
    /// 位置信息
    /// </summary>
    public readonly string Pos;
    /// <summary>
    /// NPC类型(1表示商人，2表示普通NPC)
    /// </summary>
    public readonly int Tyep;
    /// <summary>
    /// 商品列表（格式：商城配置ID:限购类型:限购数量；1每日限购，2永久限购，3无限限购；无限限购数量填0）
    /// </summary>
    public readonly string ItemList;
    /// <summary>
    /// 自言自语
    /// </summary>
    public readonly string Think;
    /// <summary>
    /// 交谈话语
    /// </summary>
    public readonly string Talk;
    /// <summary>
    /// 地图id
    /// </summary>
    public readonly int Mapid;
   
    public const int __ID__ = -488979697;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "PrefabPath:" + PrefabPath + ","
        + "Pos:" + Pos + ","
        + "tyep:" + Tyep + ","
        + "ItemList:" + ItemList + ","
        + "Think:" + Think + ","
        + "Talk:" + Talk + ","
        + "mapid:" + Mapid + ","
        + "}";
    }
}
}

