
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class ProfessionInfo : Luban.BeanBase
{
    public ProfessionInfo(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        IconPath = _buf.ReadString();
        PrefabPath = _buf.ReadString();
        BornPosition = _buf.ReadString();
        Name = _buf.ReadString();
        MaxHp = _buf.ReadInt();
        MaxMp = _buf.ReadInt();
        AtkExternalMin = _buf.ReadInt();
        AtkExternalMax = _buf.ReadInt();
        AtkInternalMin = _buf.ReadInt();
        AtkInternalMax = _buf.ReadInt();
        DefExternal = _buf.ReadInt();
        DefExternalDelta = _buf.ReadInt();
        DefInternal = _buf.ReadInt();
        DefInternalDelta = _buf.ReadInt();
        HitPoint = _buf.ReadInt();
        BlockPoint = _buf.ReadInt();
        ZhenJi = _buf.ReadInt();
        WuGu = _buf.ReadInt();
        CritPoint = _buf.ReadInt();
        CritResistPoint = _buf.ReadInt();
        CritDamage = _buf.ReadFloat();
        CritDamageReduce = _buf.ReadFloat();
        HealStrength = _buf.ReadInt();
        HealBonus = _buf.ReadFloat();
        ZhuXin = _buf.ReadInt();
        JianRen = _buf.ReadInt();
        Qi = _buf.ReadInt();
    }

    public static ProfessionInfo DeserializeProfessionInfo(ByteBuf _buf)
    {
        return new ProfessionInfo(_buf);
    }

    /// <summary>
    /// 职业 ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 职业头像资源路径
    /// </summary>
    public readonly string IconPath;
    /// <summary>
    /// 职业角色预制体资源路径
    /// </summary>
    public readonly string PrefabPath;
    /// <summary>
    /// 角色出生位置，格式 x,y,z
    /// </summary>
    public readonly string BornPosition;
    /// <summary>
    /// 职业名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 最大生命值初始数值
    /// </summary>
    public readonly int MaxHp;
    /// <summary>
    /// 最大法力值初始数值
    /// </summary>
    public readonly int MaxMp;
    /// <summary>
    /// 外功攻击最小值初始数值
    /// </summary>
    public readonly int AtkExternalMin;
    /// <summary>
    /// 外功攻击最大值初始数值
    /// </summary>
    public readonly int AtkExternalMax;
    /// <summary>
    /// 内功攻击最小值初始数值
    /// </summary>
    public readonly int AtkInternalMin;
    /// <summary>
    /// 内功攻击最大值初始数值
    /// </summary>
    public readonly int AtkInternalMax;
    /// <summary>
    /// 外功防御初始数值
    /// </summary>
    public readonly int DefExternal;
    /// <summary>
    /// 外功防御变动值初始数值
    /// </summary>
    public readonly int DefExternalDelta;
    /// <summary>
    /// 内功防御初始数值
    /// </summary>
    public readonly int DefInternal;
    /// <summary>
    /// 内功防御变动值初始数值
    /// </summary>
    public readonly int DefInternalDelta;
    /// <summary>
    /// 命中属性值初始数值
    /// </summary>
    public readonly int HitPoint;
    /// <summary>
    /// 格挡属性值初始数值
    /// </summary>
    public readonly int BlockPoint;
    /// <summary>
    /// 振击属性值初始数值
    /// </summary>
    public readonly int ZhenJi;
    /// <summary>
    /// 无咎属性值初始数值
    /// </summary>
    public readonly int WuGu;
    /// <summary>
    /// 暴击属性值初始数值
    /// </summary>
    public readonly int CritPoint;
    /// <summary>
    /// 暴抗属性值初始数值
    /// </summary>
    public readonly int CritResistPoint;
    /// <summary>
    /// 暴击伤害百分比初始数值，150 表示 150%
    /// </summary>
    public readonly float CritDamage;
    /// <summary>
    /// 暴击伤害减免百分比初始数值
    /// </summary>
    public readonly float CritDamageReduce;
    /// <summary>
    /// 治疗强度初始数值
    /// </summary>
    public readonly int HealStrength;
    /// <summary>
    /// 治疗增益百分比初始数值
    /// </summary>
    public readonly float HealBonus;
    /// <summary>
    /// 诛心初始数值
    /// </summary>
    public readonly int ZhuXin;
    /// <summary>
    /// 坚韧初始数值
    /// </summary>
    public readonly int JianRen;
    /// <summary>
    /// 气初始数值
    /// </summary>
    public readonly int Qi;
   
    public const int __ID__ = -1867143190;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "IconPath:" + IconPath + ","
        + "PrefabPath:" + PrefabPath + ","
        + "BornPosition:" + BornPosition + ","
        + "Name:" + Name + ","
        + "MaxHp:" + MaxHp + ","
        + "MaxMp:" + MaxMp + ","
        + "AtkExternalMin:" + AtkExternalMin + ","
        + "AtkExternalMax:" + AtkExternalMax + ","
        + "AtkInternalMin:" + AtkInternalMin + ","
        + "AtkInternalMax:" + AtkInternalMax + ","
        + "DefExternal:" + DefExternal + ","
        + "DefExternalDelta:" + DefExternalDelta + ","
        + "DefInternal:" + DefInternal + ","
        + "DefInternalDelta:" + DefInternalDelta + ","
        + "HitPoint:" + HitPoint + ","
        + "BlockPoint:" + BlockPoint + ","
        + "ZhenJi:" + ZhenJi + ","
        + "WuGu:" + WuGu + ","
        + "CritPoint:" + CritPoint + ","
        + "CritResistPoint:" + CritResistPoint + ","
        + "CritDamage:" + CritDamage + ","
        + "CritDamageReduce:" + CritDamageReduce + ","
        + "HealStrength:" + HealStrength + ","
        + "HealBonus:" + HealBonus + ","
        + "ZhuXin:" + ZhuXin + ","
        + "JianRen:" + JianRen + ","
        + "Qi:" + Qi + ","
        + "}";
    }
}
}

