
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class QuestInfo : Luban.BeanBase
{
    public QuestInfo(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Type = _buf.ReadInt();
        Description = _buf.ReadString();
        MinLevel = _buf.ReadInt();
        PreQuestId = _buf.ReadInt();
        AcceptNpcId = _buf.ReadInt();
        SubmitNpcId = _buf.ReadInt();
        TargetType = _buf.ReadInt();
        TargetId = _buf.ReadInt();
        TargetCount = _buf.ReadInt();
        RewardExp = _buf.ReadInt();
        RewardGold = _buf.ReadInt();
        RewardItemId = _buf.ReadInt();
        RewardItemCount = _buf.ReadInt();
        NextQuestId = _buf.ReadInt();
        IsAutoAccept = _buf.ReadBool();
        IsAutoSubmit = _buf.ReadBool();
        TimeLimit = _buf.ReadInt();
    }

    public static QuestInfo DeserializeQuestInfo(ByteBuf _buf)
    {
        return new QuestInfo(_buf);
    }

    /// <summary>
    /// 任务唯一ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 任务名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 任务类型(1主线,2支线,3日常,4循环)
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 任务描述
    /// </summary>
    public readonly string Description;
    /// <summary>
    /// 接取最低等级
    /// </summary>
    public readonly int MinLevel;
    /// <summary>
    /// 前置任务ID(0无)
    /// </summary>
    public readonly int PreQuestId;
    /// <summary>
    /// 接取NPC ID
    /// </summary>
    public readonly int AcceptNpcId;
    /// <summary>
    /// 提交NPC ID
    /// </summary>
    public readonly int SubmitNpcId;
    /// <summary>
    /// 目标类型(0无,1击杀,2收集,3对话,4到达)
    /// </summary>
    public readonly int TargetType;
    /// <summary>
    /// 目标ID
    /// </summary>
    public readonly int TargetId;
    /// <summary>
    /// 目标数量
    /// </summary>
    public readonly int TargetCount;
    /// <summary>
    /// 经验奖励
    /// </summary>
    public readonly int RewardExp;
    /// <summary>
    /// 金币奖励
    /// </summary>
    public readonly int RewardGold;
    /// <summary>
    /// 奖励道具ID(0无)
    /// </summary>
    public readonly int RewardItemId;
    /// <summary>
    /// 奖励道具数量
    /// </summary>
    public readonly int RewardItemCount;
    /// <summary>
    /// 后续任务ID(0无)
    /// </summary>
    public readonly int NextQuestId;
    /// <summary>
    /// 是否自动接取
    /// </summary>
    public readonly bool IsAutoAccept;
    /// <summary>
    /// 是否自动提交
    /// </summary>
    public readonly bool IsAutoSubmit;
    /// <summary>
    /// 限时秒数(0不限)
    /// </summary>
    public readonly int TimeLimit;
   
    public const int __ID__ = 220778640;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Type:" + Type + ","
        + "Description:" + Description + ","
        + "MinLevel:" + MinLevel + ","
        + "PreQuestId:" + PreQuestId + ","
        + "AcceptNpcId:" + AcceptNpcId + ","
        + "SubmitNpcId:" + SubmitNpcId + ","
        + "TargetType:" + TargetType + ","
        + "TargetId:" + TargetId + ","
        + "TargetCount:" + TargetCount + ","
        + "RewardExp:" + RewardExp + ","
        + "RewardGold:" + RewardGold + ","
        + "RewardItemId:" + RewardItemId + ","
        + "RewardItemCount:" + RewardItemCount + ","
        + "NextQuestId:" + NextQuestId + ","
        + "IsAutoAccept:" + IsAutoAccept + ","
        + "IsAutoSubmit:" + IsAutoSubmit + ","
        + "TimeLimit:" + TimeLimit + ","
        + "}";
    }
}
}

