
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class RoleLevelAttributeInfo : Luban.BeanBase
{
    public RoleLevelAttributeInfo(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        JobId = _buf.ReadInt();
        Level = _buf.ReadInt();
        MaxHp = _buf.ReadInt();
        MaxMp = _buf.ReadInt();
        AtkExternalMin = _buf.ReadInt();
        AtkExternalMax = _buf.ReadInt();
        AtkInternalMin = _buf.ReadInt();
        AtkInternalMax = _buf.ReadInt();
        DefExternal = _buf.ReadInt();
        DefExternalDelta = _buf.ReadInt();
        DefInternal = _buf.ReadInt();
        DefInternalDelta = _buf.ReadInt();
        HitPoint = _buf.ReadInt();
        BlockPoint = _buf.ReadInt();
        ZhenJi = _buf.ReadInt();
        WuGu = _buf.ReadInt();
        CritPoint = _buf.ReadInt();
        CritResistPoint = _buf.ReadInt();
        CritDamage = _buf.ReadFloat();
        CritDamageReduce = _buf.ReadFloat();
        HealStrength = _buf.ReadInt();
        HealBonus = _buf.ReadFloat();
        ZhuXin = _buf.ReadInt();
        JianRen = _buf.ReadInt();
        Qi = _buf.ReadInt();
    }

    public static RoleLevelAttributeInfo DeserializeRoleLevelAttributeInfo(ByteBuf _buf)
    {
        return new RoleLevelAttributeInfo(_buf);
    }

    /// <summary>
    /// 配置 ID，规则 JobId * 1000 + Level
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 职业 ID，关联 ProfessionInfo.Id
    /// </summary>
    public readonly int JobId;
    /// <summary>
    /// 升级到该等级时获得以下属性；1 级为 0，基础属性由 ProfessionInfo 提供
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 最大生命值增加值
    /// </summary>
    public readonly int MaxHp;
    /// <summary>
    /// 最大法力值增加值
    /// </summary>
    public readonly int MaxMp;
    /// <summary>
    /// 外功攻击最小值增加值
    /// </summary>
    public readonly int AtkExternalMin;
    /// <summary>
    /// 外功攻击最大值增加值
    /// </summary>
    public readonly int AtkExternalMax;
    /// <summary>
    /// 内功攻击最小值增加值
    /// </summary>
    public readonly int AtkInternalMin;
    /// <summary>
    /// 内功攻击最大值增加值
    /// </summary>
    public readonly int AtkInternalMax;
    /// <summary>
    /// 外功防御增加值
    /// </summary>
    public readonly int DefExternal;
    /// <summary>
    /// 外功防御变动值增加值
    /// </summary>
    public readonly int DefExternalDelta;
    /// <summary>
    /// 内功防御增加值
    /// </summary>
    public readonly int DefInternal;
    /// <summary>
    /// 内功防御变动值增加值
    /// </summary>
    public readonly int DefInternalDelta;
    /// <summary>
    /// 命中属性值增加值
    /// </summary>
    public readonly int HitPoint;
    /// <summary>
    /// 格挡属性值增加值
    /// </summary>
    public readonly int BlockPoint;
    /// <summary>
    /// 振击属性值增加值
    /// </summary>
    public readonly int ZhenJi;
    /// <summary>
    /// 无咎属性值增加值
    /// </summary>
    public readonly int WuGu;
    /// <summary>
    /// 暴击属性值增加值
    /// </summary>
    public readonly int CritPoint;
    /// <summary>
    /// 暴抗属性值增加值
    /// </summary>
    public readonly int CritResistPoint;
    /// <summary>
    /// 暴击伤害百分比增加值
    /// </summary>
    public readonly float CritDamage;
    /// <summary>
    /// 暴击伤害减免百分比增加值
    /// </summary>
    public readonly float CritDamageReduce;
    /// <summary>
    /// 治疗强度增加值
    /// </summary>
    public readonly int HealStrength;
    /// <summary>
    /// 治疗增益百分比增加值
    /// </summary>
    public readonly float HealBonus;
    /// <summary>
    /// 诛心增加值
    /// </summary>
    public readonly int ZhuXin;
    /// <summary>
    /// 坚韧增加值
    /// </summary>
    public readonly int JianRen;
    /// <summary>
    /// 气增加值
    /// </summary>
    public readonly int Qi;
   
    public const int __ID__ = 664024956;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "JobId:" + JobId + ","
        + "Level:" + Level + ","
        + "MaxHp:" + MaxHp + ","
        + "MaxMp:" + MaxMp + ","
        + "AtkExternalMin:" + AtkExternalMin + ","
        + "AtkExternalMax:" + AtkExternalMax + ","
        + "AtkInternalMin:" + AtkInternalMin + ","
        + "AtkInternalMax:" + AtkInternalMax + ","
        + "DefExternal:" + DefExternal + ","
        + "DefExternalDelta:" + DefExternalDelta + ","
        + "DefInternal:" + DefInternal + ","
        + "DefInternalDelta:" + DefInternalDelta + ","
        + "HitPoint:" + HitPoint + ","
        + "BlockPoint:" + BlockPoint + ","
        + "ZhenJi:" + ZhenJi + ","
        + "WuGu:" + WuGu + ","
        + "CritPoint:" + CritPoint + ","
        + "CritResistPoint:" + CritResistPoint + ","
        + "CritDamage:" + CritDamage + ","
        + "CritDamageReduce:" + CritDamageReduce + ","
        + "HealStrength:" + HealStrength + ","
        + "HealBonus:" + HealBonus + ","
        + "ZhuXin:" + ZhuXin + ","
        + "JianRen:" + JianRen + ","
        + "Qi:" + Qi + ","
        + "}";
    }
}
}

