
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class RoleLevelInfo : Luban.BeanBase
{
    public RoleLevelInfo(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Level = _buf.ReadInt();
        NeedExp = _buf.ReadInt();
    }

    public static RoleLevelInfo DeserializeRoleLevelInfo(ByteBuf _buf)
    {
        return new RoleLevelInfo(_buf);
    }

    /// <summary>
    /// 配置 ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 角色等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 从当前等级升级到下一等级所需经验；满级为 0
    /// </summary>
    public readonly int NeedExp;
   
    public const int __ID__ = 36243036;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Level:" + Level + ","
        + "NeedExp:" + NeedExp + ","
        + "}";
    }
}
}

