
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class ShopTable : Luban.BeanBase
{
    public ShopTable(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        ShopType = _buf.ReadInt();
        CurrencyType = _buf.ReadInt();
        IsStatic = _buf.ReadInt();
        SceneLimit = _buf.ReadInt();
        SystemId = _buf.ReadInt();
        Description = _buf.ReadString();
    }

    public static ShopTable DeserializeShopTable(ByteBuf _buf)
    {
        return new ShopTable(_buf);
    }

    /// <summary>
    /// 商店ID，供ShopItemInfo.ShopId引用
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 商店名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 商店类型(1 NPC,2商城,3活动)
    /// </summary>
    public readonly int ShopType;
    /// <summary>
    /// 货币类型
    /// </summary>
    public readonly int CurrencyType;
    /// <summary>
    /// 是否静态(0是,1否)
    /// </summary>
    public readonly int IsStatic;
    /// <summary>
    /// 场景限制(0不限)
    /// </summary>
    public readonly int SceneLimit;
    /// <summary>
    /// 关联系统ID(0无)
    /// </summary>
    public readonly int SystemId;
    /// <summary>
    /// 商店说明
    /// </summary>
    public readonly string Description;
   
    public const int __ID__ = -110495144;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "ShopType:" + ShopType + ","
        + "CurrencyType:" + CurrencyType + ","
        + "IsStatic:" + IsStatic + ","
        + "SceneLimit:" + SceneLimit + ","
        + "SystemId:" + SystemId + ","
        + "Description:" + Description + ","
        + "}";
    }
}
}

