
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class ShopItemInfo : Luban.BeanBase
{
    public ShopItemInfo(ByteBuf _buf) 
    {
        GoodsId = _buf.ReadInt();
        ItemId = _buf.ReadInt();
        Price = _buf.ReadInt();
        CurrencyItemId = _buf.ReadInt();
        BindAfterPurchase = _buf.ReadInt();
        ShopId = _buf.ReadInt();
        ItemName = _buf.ReadString();
        ItemPerMount = _buf.ReadInt();
        IsUnlocked = _buf.ReadInt();
        JobLimit = _buf.ReadInt();
        BaseLevelLimit = _buf.ReadInt();
        QuestLimit = _buf.ReadInt();
        StartTime = _buf.ReadString();
        EndTime = _buf.ReadString();
        Discount = _buf.ReadInt();
        PriceChange = _buf.ReadString();
        列1 = _buf.ReadInt();
        列2 = _buf.ReadString();
    }

    public static ShopItemInfo DeserializeShopItemInfo(ByteBuf _buf)
    {
        return new ShopItemInfo(_buf);
    }

    /// <summary>
    /// 商城商品配置 ID（商品主键）
    /// </summary>
    public readonly int GoodsId;
    /// <summary>
    /// 物品配置ID
    /// </summary>
    public readonly int ItemId;
    /// <summary>
    /// 售价
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 货币物品ID，对应 #ItemInfo.ItemTypeId
    /// </summary>
    public readonly int CurrencyItemId;
    /// <summary>
    /// 购买后是否绑定(0否,1是)
    /// </summary>
    public readonly int BindAfterPurchase;
    /// <summary>
    /// 所属商店ID，关联ShopTable.Id
    /// </summary>
    public readonly int ShopId;
    /// <summary>
    /// 商品名称
    /// </summary>
    public readonly string ItemName;
    /// <summary>
    /// 单次购买数量
    /// </summary>
    public readonly int ItemPerMount;
    /// <summary>
    /// 是否解锁(0否,1是)
    /// </summary>
    public readonly int IsUnlocked;
    /// <summary>
    /// 职业限制(0不限)
    /// </summary>
    public readonly int JobLimit;
    /// <summary>
    /// 最低等级限制(0不限)
    /// </summary>
    public readonly int BaseLevelLimit;
    /// <summary>
    /// 任务限制(0不限)
    /// </summary>
    public readonly int QuestLimit;
    /// <summary>
    /// 开始时间(空不限)
    /// </summary>
    public readonly string StartTime;
    /// <summary>
    /// 结束时间(空不限)
    /// </summary>
    public readonly string EndTime;
    /// <summary>
    /// 折扣(百分比，0无)
    /// </summary>
    public readonly int Discount;
    /// <summary>
    /// 价格变动规则
    /// </summary>
    public readonly string PriceChange;
    /// <summary>
    /// 折扣(百分比，0无)
    /// </summary>
    public readonly int 列1;
    /// <summary>
    /// 价格变动规则
    /// </summary>
    public readonly string 列2;
   
    public const int __ID__ = 256823191;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "GoodsId:" + GoodsId + ","
        + "ItemId:" + ItemId + ","
        + "Price:" + Price + ","
        + "CurrencyItemId:" + CurrencyItemId + ","
        + "BindAfterPurchase:" + BindAfterPurchase + ","
        + "ShopId:" + ShopId + ","
        + "ItemName:" + ItemName + ","
        + "ItemPerMount:" + ItemPerMount + ","
        + "IsUnlocked:" + IsUnlocked + ","
        + "JobLimit:" + JobLimit + ","
        + "BaseLevelLimit:" + BaseLevelLimit + ","
        + "QuestLimit:" + QuestLimit + ","
        + "StartTime:" + StartTime + ","
        + "EndTime:" + EndTime + ","
        + "Discount:" + Discount + ","
        + "PriceChange:" + PriceChange + ","
        + "列1:" + 列1 + ","
        + "列2:" + 列2 + ","
        + "}";
    }
}
}

