
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class ShopInfo : Luban.BeanBase
{
    public ShopInfo(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ItemId = _buf.ReadInt();
        Price = _buf.ReadInt();
        CurrencyType = _buf.ReadInt();
        BindAfterPurchase = _buf.ReadInt();
    }

    public static ShopInfo DeserializeShopInfo(ByteBuf _buf)
    {
        return new ShopInfo(_buf);
    }

    /// <summary>
    /// 商城商品配置ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 物品配置ID
    /// </summary>
    public readonly int ItemId;
    /// <summary>
    /// 售价
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 货币类型
    /// </summary>
    public readonly int CurrencyType;
    /// <summary>
    /// 购买后是否绑定(0否,1是)
    /// </summary>
    public readonly int BindAfterPurchase;
   
    public const int __ID__ = -280974108;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "ItemId:" + ItemId + ","
        + "Price:" + Price + ","
        + "CurrencyType:" + CurrencyType + ","
        + "BindAfterPurchase:" + BindAfterPurchase + ","
        + "}";
    }
}
}

