
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace cfg
{
public partial class Tables
{
    public TbCountInfo TbCountInfo {get; }
    public TbEquipInfo TbEquipInfo {get; }
    public TbGene TbGene {get; }
    public TbItemInfo TbItemInfo {get; }
    public TbKnapsackInfo TbKnapsackInfo {get; }
    public TbNpcInfo TbNpcInfo {get; }
    public TbProfessionInfo TbProfessionInfo {get; }
    public TbQuestInfo TbQuestInfo {get; }
    public TbRoleLevelAttributeInfo TbRoleLevelAttributeInfo {get; }
    public TbRoleLevelInfo TbRoleLevelInfo {get; }
    public TbShopItemInfo TbShopItemInfo {get; }
    public TbShopTable TbShopTable {get; }
    public TbSkillInfo TbSkillInfo {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbCountInfo = new TbCountInfo(loader("tbcountinfo"));
        TbEquipInfo = new TbEquipInfo(loader("tbequipinfo"));
        TbGene = new TbGene(loader("tbgene"));
        TbItemInfo = new TbItemInfo(loader("tbiteminfo"));
        TbKnapsackInfo = new TbKnapsackInfo(loader("tbknapsackinfo"));
        TbNpcInfo = new TbNpcInfo(loader("tbnpcinfo"));
        TbProfessionInfo = new TbProfessionInfo(loader("tbprofessioninfo"));
        TbQuestInfo = new TbQuestInfo(loader("tbquestinfo"));
        TbRoleLevelAttributeInfo = new TbRoleLevelAttributeInfo(loader("tbrolelevelattributeinfo"));
        TbRoleLevelInfo = new TbRoleLevelInfo(loader("tbrolelevelinfo"));
        TbShopItemInfo = new TbShopItemInfo(loader("tbshopiteminfo"));
        TbShopTable = new TbShopTable(loader("tbshoptable"));
        TbSkillInfo = new TbSkillInfo(loader("tbskillinfo"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbCountInfo.ResolveRef(this);
        TbEquipInfo.ResolveRef(this);
        TbGene.ResolveRef(this);
        TbItemInfo.ResolveRef(this);
        TbKnapsackInfo.ResolveRef(this);
        TbNpcInfo.ResolveRef(this);
        TbProfessionInfo.ResolveRef(this);
        TbQuestInfo.ResolveRef(this);
        TbRoleLevelAttributeInfo.ResolveRef(this);
        TbRoleLevelInfo.ResolveRef(this);
        TbShopItemInfo.ResolveRef(this);
        TbShopTable.ResolveRef(this);
        TbSkillInfo.ResolveRef(this);
    }
}

}
