
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbCountInfo
{
    private readonly System.Collections.Generic.Dictionary<int, CountInfo> _dataMap;
    private readonly System.Collections.Generic.List<CountInfo> _dataList;
    
    public TbCountInfo(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, CountInfo>(n);
        _dataList = new System.Collections.Generic.List<CountInfo>(n);
        for(int i = n ; i > 0 ; --i)
        {
            CountInfo _v;
            _v = global::cfg.CountInfo.DeserializeCountInfo(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, CountInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<CountInfo> DataList => _dataList;

    public CountInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public CountInfo Get(int key) => _dataMap[key];
    public CountInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

