
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbEquipInfo
{
    private readonly System.Collections.Generic.Dictionary<int, EquipInfo> _dataMap;
    private readonly System.Collections.Generic.List<EquipInfo> _dataList;
    
    public TbEquipInfo(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, EquipInfo>(n);
        _dataList = new System.Collections.Generic.List<EquipInfo>(n);
        for(int i = n ; i > 0 ; --i)
        {
            EquipInfo _v;
            _v = global::cfg.EquipInfo.DeserializeEquipInfo(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ItemTypeId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, EquipInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<EquipInfo> DataList => _dataList;

    public EquipInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public EquipInfo Get(int key) => _dataMap[key];
    public EquipInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

