
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbGene
{
    private readonly System.Collections.Generic.Dictionary<int, Gene> _dataMap;
    private readonly System.Collections.Generic.List<Gene> _dataList;
    
    public TbGene(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Gene>(n);
        _dataList = new System.Collections.Generic.List<Gene>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Gene _v;
            _v = global::cfg.Gene.DeserializeGene(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Gene> DataMap => _dataMap;
    public System.Collections.Generic.List<Gene> DataList => _dataList;

    public Gene GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Gene Get(int key) => _dataMap[key];
    public Gene this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

