
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbItemInfo
{
    private readonly System.Collections.Generic.Dictionary<int, ItemInfo> _dataMap;
    private readonly System.Collections.Generic.List<ItemInfo> _dataList;
    
    public TbItemInfo(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, ItemInfo>(n);
        _dataList = new System.Collections.Generic.List<ItemInfo>(n);
        for(int i = n ; i > 0 ; --i)
        {
            ItemInfo _v;
            _v = global::cfg.ItemInfo.DeserializeItemInfo(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ItemTypeId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ItemInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<ItemInfo> DataList => _dataList;

    public ItemInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ItemInfo Get(int key) => _dataMap[key];
    public ItemInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

