
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbNpcInfo
{
    private readonly System.Collections.Generic.Dictionary<int, NpcInfo> _dataMap;
    private readonly System.Collections.Generic.List<NpcInfo> _dataList;
    
    public TbNpcInfo(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, NpcInfo>(n);
        _dataList = new System.Collections.Generic.List<NpcInfo>(n);
        for(int i = n ; i > 0 ; --i)
        {
            NpcInfo _v;
            _v = global::cfg.NpcInfo.DeserializeNpcInfo(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, NpcInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<NpcInfo> DataList => _dataList;

    public NpcInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public NpcInfo Get(int key) => _dataMap[key];
    public NpcInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

