
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbProfessionInfo
{
    private readonly System.Collections.Generic.Dictionary<int, ProfessionInfo> _dataMap;
    private readonly System.Collections.Generic.List<ProfessionInfo> _dataList;
    
    public TbProfessionInfo(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, ProfessionInfo>(n);
        _dataList = new System.Collections.Generic.List<ProfessionInfo>(n);
        for(int i = n ; i > 0 ; --i)
        {
            ProfessionInfo _v;
            _v = global::cfg.ProfessionInfo.DeserializeProfessionInfo(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ProfessionInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<ProfessionInfo> DataList => _dataList;

    public ProfessionInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ProfessionInfo Get(int key) => _dataMap[key];
    public ProfessionInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

