
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbQuestInfo
{
    private readonly System.Collections.Generic.Dictionary<int, QuestInfo> _dataMap;
    private readonly System.Collections.Generic.List<QuestInfo> _dataList;
    
    public TbQuestInfo(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, QuestInfo>(n);
        _dataList = new System.Collections.Generic.List<QuestInfo>(n);
        for(int i = n ; i > 0 ; --i)
        {
            QuestInfo _v;
            _v = global::cfg.QuestInfo.DeserializeQuestInfo(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, QuestInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<QuestInfo> DataList => _dataList;

    public QuestInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public QuestInfo Get(int key) => _dataMap[key];
    public QuestInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

