
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbRoleLevelAttributeInfo
{
    private readonly System.Collections.Generic.Dictionary<int, RoleLevelAttributeInfo> _dataMap;
    private readonly System.Collections.Generic.List<RoleLevelAttributeInfo> _dataList;
    
    public TbRoleLevelAttributeInfo(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, RoleLevelAttributeInfo>(n);
        _dataList = new System.Collections.Generic.List<RoleLevelAttributeInfo>(n);
        for(int i = n ; i > 0 ; --i)
        {
            RoleLevelAttributeInfo _v;
            _v = global::cfg.RoleLevelAttributeInfo.DeserializeRoleLevelAttributeInfo(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, RoleLevelAttributeInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<RoleLevelAttributeInfo> DataList => _dataList;

    public RoleLevelAttributeInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public RoleLevelAttributeInfo Get(int key) => _dataMap[key];
    public RoleLevelAttributeInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

