
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbShopTable
{
    private readonly System.Collections.Generic.Dictionary<int, ShopTable> _dataMap;
    private readonly System.Collections.Generic.List<ShopTable> _dataList;
    
    public TbShopTable(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, ShopTable>(n);
        _dataList = new System.Collections.Generic.List<ShopTable>(n);
        for(int i = n ; i > 0 ; --i)
        {
            ShopTable _v;
            _v = global::cfg.ShopTable.DeserializeShopTable(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ShopTable> DataMap => _dataMap;
    public System.Collections.Generic.List<ShopTable> DataList => _dataList;

    public ShopTable GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ShopTable Get(int key) => _dataMap[key];
    public ShopTable this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

