
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbShopInfo
{
    private readonly System.Collections.Generic.Dictionary<int, ShopInfo> _dataMap;
    private readonly System.Collections.Generic.List<ShopInfo> _dataList;
    
    public TbShopInfo(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, ShopInfo>(n);
        _dataList = new System.Collections.Generic.List<ShopInfo>(n);
        for(int i = n ; i > 0 ; --i)
        {
            ShopInfo _v;
            _v = global::cfg.ShopInfo.DeserializeShopInfo(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ShopInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<ShopInfo> DataList => _dataList;

    public ShopInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ShopInfo Get(int key) => _dataMap[key];
    public ShopInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

