
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbShopItemInfo
{
    private readonly System.Collections.Generic.Dictionary<int, ShopItemInfo> _dataMap;
    private readonly System.Collections.Generic.List<ShopItemInfo> _dataList;
    
    public TbShopItemInfo(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, ShopItemInfo>(n);
        _dataList = new System.Collections.Generic.List<ShopItemInfo>(n);
        for(int i = n ; i > 0 ; --i)
        {
            ShopItemInfo _v;
            _v = global::cfg.ShopItemInfo.DeserializeShopItemInfo(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.GoodsId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ShopItemInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<ShopItemInfo> DataList => _dataList;

    public ShopItemInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ShopItemInfo Get(int key) => _dataMap[key];
    public ShopItemInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

