
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbWalletInfo
{
    private readonly System.Collections.Generic.Dictionary<int, WalletInfo> _dataMap;
    private readonly System.Collections.Generic.List<WalletInfo> _dataList;
    
    public TbWalletInfo(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, WalletInfo>(n);
        _dataList = new System.Collections.Generic.List<WalletInfo>(n);
        for(int i = n ; i > 0 ; --i)
        {
            WalletInfo _v;
            _v = global::cfg.WalletInfo.DeserializeWalletInfo(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.CurrencyType, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, WalletInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<WalletInfo> DataList => _dataList;

    public WalletInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public WalletInfo Get(int key) => _dataMap[key];
    public WalletInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

