
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class WalletInfo : Luban.BeanBase
{
    public WalletInfo(ByteBuf _buf) 
    {
        CurrencyType = _buf.ReadInt();
        CurrencyName = _buf.ReadString();
        CurrencyIconPath = _buf.ReadString();
    }

    public static WalletInfo DeserializeWalletInfo(ByteBuf _buf)
    {
        return new WalletInfo(_buf);
    }

    /// <summary>
    /// 货币类型
    /// </summary>
    public readonly int CurrencyType;
    /// <summary>
    /// 货币名称
    /// </summary>
    public readonly string CurrencyName;
    /// <summary>
    /// 货币图标资源路径
    /// </summary>
    public readonly string CurrencyIconPath;
   
    public const int __ID__ = 165831783;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "CurrencyType:" + CurrencyType + ","
        + "CurrencyName:" + CurrencyName + ","
        + "CurrencyIconPath:" + CurrencyIconPath + ","
        + "}";
    }
}
}

